# file: .github/workflows/workflow.yml
name: hexlet-ci-app
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен, выполняет какую-то задачу
      # checkout – клонирует репозиторий
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Setup build
        run: make setup
      - name: test
        run: make test
      - name: lint
        run: make lint
